apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-oppslag-ytelser
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{ image }}"
  port: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  azure:
    application:
      enabled: true
  startup:
    path: /isalive
    initialDelay: 10
    failureThreshold: 6
    periodSeconds: 5
    timeout: 1
  liveness:
    path: /isalive
    failureThreshold: 6
    periodSeconds: 10
  readiness:
    path: /isready
    failureThreshold: 3
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 81m
      memory: 448Mi
  replicas:
    min: 1
    max: 2
  accessPolicy:
    outbound:
      external:
        - host: fpabakus.{{cluster.fss}}-pub.nais.io
        - host: pensjon-pen.{{cluster.fss}}-pub.nais.io
      rules:
        - application: spokelse
          namespace: tbd
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=25.0 -XX:ActiveProcessorCount=4
  kafka:
    pool: "{{ kafka.pool }}"
  secureLogs:
    enabled: true
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
